//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace benhxaCA.Report {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("ThongTinReport")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class ThongTinReport : global::System.Data.DataSet {
        
        private GET_THONGTINCANBODataTable tableGET_THONGTINCANBO;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public ThongTinReport() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected ThongTinReport(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["GET_THONGTINCANBO"] != null)) {
                    base.Tables.Add(new GET_THONGTINCANBODataTable(ds.Tables["GET_THONGTINCANBO"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public GET_THONGTINCANBODataTable GET_THONGTINCANBO {
            get {
                return this.tableGET_THONGTINCANBO;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            ThongTinReport cln = ((ThongTinReport)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["GET_THONGTINCANBO"] != null)) {
                    base.Tables.Add(new GET_THONGTINCANBODataTable(ds.Tables["GET_THONGTINCANBO"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableGET_THONGTINCANBO = ((GET_THONGTINCANBODataTable)(base.Tables["GET_THONGTINCANBO"]));
            if ((initTable == true)) {
                if ((this.tableGET_THONGTINCANBO != null)) {
                    this.tableGET_THONGTINCANBO.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "ThongTinReport";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/ThongTinReport.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableGET_THONGTINCANBO = new GET_THONGTINCANBODataTable();
            base.Tables.Add(this.tableGET_THONGTINCANBO);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeGET_THONGTINCANBO() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            ThongTinReport ds = new ThongTinReport();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void GET_THONGTINCANBORowChangeEventHandler(object sender, GET_THONGTINCANBORowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class GET_THONGTINCANBODataTable : global::System.Data.TypedTableBase<GET_THONGTINCANBORow> {
            
            private global::System.Data.DataColumn columnttcb_hoten;
            
            private global::System.Data.DataColumn columnttcb_ngaysinh;
            
            private global::System.Data.DataColumn columnttcb_gioitinh;
            
            private global::System.Data.DataColumn columnttcb_cmnd_or_cccd;
            
            private global::System.Data.DataColumn columnttcb_dantoc;
            
            private global::System.Data.DataColumn columnttcb_sodienthoai;
            
            private global::System.Data.DataColumn columnttcb_hokhauthuongtru;
            
            private global::System.Data.DataColumn columnttcb_choohiennay;
            
            private global::System.Data.DataColumn columnttcb_hinhanh;
            
            private global::System.Data.DataColumn columndv_ten;
            
            private global::System.Data.DataColumn columnkl_loaisuckhoe;
            
            private global::System.Data.DataColumn columnkl_ketluantong;
            
            private global::System.Data.DataColumn columndksk_ngaykham;
            
            private global::System.Data.DataColumn columnlslv_ngaybatdaulamviec;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GET_THONGTINCANBODataTable() {
                this.TableName = "GET_THONGTINCANBO";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal GET_THONGTINCANBODataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected GET_THONGTINCANBODataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ttcb_hotenColumn {
                get {
                    return this.columnttcb_hoten;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ttcb_ngaysinhColumn {
                get {
                    return this.columnttcb_ngaysinh;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ttcb_gioitinhColumn {
                get {
                    return this.columnttcb_gioitinh;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ttcb_cmnd_or_cccdColumn {
                get {
                    return this.columnttcb_cmnd_or_cccd;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ttcb_dantocColumn {
                get {
                    return this.columnttcb_dantoc;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ttcb_sodienthoaiColumn {
                get {
                    return this.columnttcb_sodienthoai;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ttcb_hokhauthuongtruColumn {
                get {
                    return this.columnttcb_hokhauthuongtru;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ttcb_choohiennayColumn {
                get {
                    return this.columnttcb_choohiennay;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ttcb_hinhanhColumn {
                get {
                    return this.columnttcb_hinhanh;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn dv_tenColumn {
                get {
                    return this.columndv_ten;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn kl_loaisuckhoeColumn {
                get {
                    return this.columnkl_loaisuckhoe;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn kl_ketluantongColumn {
                get {
                    return this.columnkl_ketluantong;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn dksk_ngaykhamColumn {
                get {
                    return this.columndksk_ngaykham;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn lslv_ngaybatdaulamviecColumn {
                get {
                    return this.columnlslv_ngaybatdaulamviec;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GET_THONGTINCANBORow this[int index] {
                get {
                    return ((GET_THONGTINCANBORow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event GET_THONGTINCANBORowChangeEventHandler GET_THONGTINCANBORowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event GET_THONGTINCANBORowChangeEventHandler GET_THONGTINCANBORowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event GET_THONGTINCANBORowChangeEventHandler GET_THONGTINCANBORowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event GET_THONGTINCANBORowChangeEventHandler GET_THONGTINCANBORowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddGET_THONGTINCANBORow(GET_THONGTINCANBORow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GET_THONGTINCANBORow AddGET_THONGTINCANBORow(string ttcb_hoten, string ttcb_ngaysinh, bool ttcb_gioitinh, string ttcb_cmnd_or_cccd, string ttcb_dantoc, string ttcb_sodienthoai, string ttcb_hokhauthuongtru, string ttcb_choohiennay, string ttcb_hinhanh, string dv_ten, int kl_loaisuckhoe, string kl_ketluantong, string dksk_ngaykham, string lslv_ngaybatdaulamviec) {
                GET_THONGTINCANBORow rowGET_THONGTINCANBORow = ((GET_THONGTINCANBORow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        ttcb_hoten,
                        ttcb_ngaysinh,
                        ttcb_gioitinh,
                        ttcb_cmnd_or_cccd,
                        ttcb_dantoc,
                        ttcb_sodienthoai,
                        ttcb_hokhauthuongtru,
                        ttcb_choohiennay,
                        ttcb_hinhanh,
                        dv_ten,
                        kl_loaisuckhoe,
                        kl_ketluantong,
                        dksk_ngaykham,
                        lslv_ngaybatdaulamviec};
                rowGET_THONGTINCANBORow.ItemArray = columnValuesArray;
                this.Rows.Add(rowGET_THONGTINCANBORow);
                return rowGET_THONGTINCANBORow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                GET_THONGTINCANBODataTable cln = ((GET_THONGTINCANBODataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new GET_THONGTINCANBODataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnttcb_hoten = base.Columns["ttcb_hoten"];
                this.columnttcb_ngaysinh = base.Columns["ttcb_ngaysinh"];
                this.columnttcb_gioitinh = base.Columns["ttcb_gioitinh"];
                this.columnttcb_cmnd_or_cccd = base.Columns["ttcb_cmnd_or_cccd"];
                this.columnttcb_dantoc = base.Columns["ttcb_dantoc"];
                this.columnttcb_sodienthoai = base.Columns["ttcb_sodienthoai"];
                this.columnttcb_hokhauthuongtru = base.Columns["ttcb_hokhauthuongtru"];
                this.columnttcb_choohiennay = base.Columns["ttcb_choohiennay"];
                this.columnttcb_hinhanh = base.Columns["ttcb_hinhanh"];
                this.columndv_ten = base.Columns["dv_ten"];
                this.columnkl_loaisuckhoe = base.Columns["kl_loaisuckhoe"];
                this.columnkl_ketluantong = base.Columns["kl_ketluantong"];
                this.columndksk_ngaykham = base.Columns["dksk_ngaykham"];
                this.columnlslv_ngaybatdaulamviec = base.Columns["lslv_ngaybatdaulamviec"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnttcb_hoten = new global::System.Data.DataColumn("ttcb_hoten", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnttcb_hoten);
                this.columnttcb_ngaysinh = new global::System.Data.DataColumn("ttcb_ngaysinh", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnttcb_ngaysinh);
                this.columnttcb_gioitinh = new global::System.Data.DataColumn("ttcb_gioitinh", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnttcb_gioitinh);
                this.columnttcb_cmnd_or_cccd = new global::System.Data.DataColumn("ttcb_cmnd_or_cccd", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnttcb_cmnd_or_cccd);
                this.columnttcb_dantoc = new global::System.Data.DataColumn("ttcb_dantoc", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnttcb_dantoc);
                this.columnttcb_sodienthoai = new global::System.Data.DataColumn("ttcb_sodienthoai", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnttcb_sodienthoai);
                this.columnttcb_hokhauthuongtru = new global::System.Data.DataColumn("ttcb_hokhauthuongtru", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnttcb_hokhauthuongtru);
                this.columnttcb_choohiennay = new global::System.Data.DataColumn("ttcb_choohiennay", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnttcb_choohiennay);
                this.columnttcb_hinhanh = new global::System.Data.DataColumn("ttcb_hinhanh", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnttcb_hinhanh);
                this.columndv_ten = new global::System.Data.DataColumn("dv_ten", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndv_ten);
                this.columnkl_loaisuckhoe = new global::System.Data.DataColumn("kl_loaisuckhoe", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnkl_loaisuckhoe);
                this.columnkl_ketluantong = new global::System.Data.DataColumn("kl_ketluantong", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnkl_ketluantong);
                this.columndksk_ngaykham = new global::System.Data.DataColumn("dksk_ngaykham", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndksk_ngaykham);
                this.columnlslv_ngaybatdaulamviec = new global::System.Data.DataColumn("lslv_ngaybatdaulamviec", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnlslv_ngaybatdaulamviec);
                this.columnttcb_hoten.MaxLength = 50;
                this.columnttcb_ngaysinh.ReadOnly = true;
                this.columnttcb_ngaysinh.MaxLength = 10;
                this.columnttcb_cmnd_or_cccd.MaxLength = 12;
                this.columnttcb_dantoc.MaxLength = 20;
                this.columnttcb_sodienthoai.MaxLength = 10;
                this.columnttcb_hokhauthuongtru.MaxLength = 200;
                this.columnttcb_choohiennay.MaxLength = 200;
                this.columnttcb_hinhanh.MaxLength = 100;
                this.columndv_ten.MaxLength = 50;
                this.columnkl_loaisuckhoe.AllowDBNull = false;
                this.columnkl_ketluantong.MaxLength = 1073741823;
                this.columndksk_ngaykham.ReadOnly = true;
                this.columndksk_ngaykham.MaxLength = 10;
                this.columnlslv_ngaybatdaulamviec.ReadOnly = true;
                this.columnlslv_ngaybatdaulamviec.MaxLength = 10;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GET_THONGTINCANBORow NewGET_THONGTINCANBORow() {
                return ((GET_THONGTINCANBORow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new GET_THONGTINCANBORow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(GET_THONGTINCANBORow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.GET_THONGTINCANBORowChanged != null)) {
                    this.GET_THONGTINCANBORowChanged(this, new GET_THONGTINCANBORowChangeEvent(((GET_THONGTINCANBORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.GET_THONGTINCANBORowChanging != null)) {
                    this.GET_THONGTINCANBORowChanging(this, new GET_THONGTINCANBORowChangeEvent(((GET_THONGTINCANBORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.GET_THONGTINCANBORowDeleted != null)) {
                    this.GET_THONGTINCANBORowDeleted(this, new GET_THONGTINCANBORowChangeEvent(((GET_THONGTINCANBORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.GET_THONGTINCANBORowDeleting != null)) {
                    this.GET_THONGTINCANBORowDeleting(this, new GET_THONGTINCANBORowChangeEvent(((GET_THONGTINCANBORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveGET_THONGTINCANBORow(GET_THONGTINCANBORow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                ThongTinReport ds = new ThongTinReport();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "GET_THONGTINCANBODataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class GET_THONGTINCANBORow : global::System.Data.DataRow {
            
            private GET_THONGTINCANBODataTable tableGET_THONGTINCANBO;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal GET_THONGTINCANBORow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableGET_THONGTINCANBO = ((GET_THONGTINCANBODataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ttcb_hoten {
                get {
                    try {
                        return ((string)(this[this.tableGET_THONGTINCANBO.ttcb_hotenColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ttcb_hoten\' in table \'GET_THONGTINCANBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGET_THONGTINCANBO.ttcb_hotenColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ttcb_ngaysinh {
                get {
                    try {
                        return ((string)(this[this.tableGET_THONGTINCANBO.ttcb_ngaysinhColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ttcb_ngaysinh\' in table \'GET_THONGTINCANBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGET_THONGTINCANBO.ttcb_ngaysinhColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool ttcb_gioitinh {
                get {
                    try {
                        return ((bool)(this[this.tableGET_THONGTINCANBO.ttcb_gioitinhColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ttcb_gioitinh\' in table \'GET_THONGTINCANBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGET_THONGTINCANBO.ttcb_gioitinhColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ttcb_cmnd_or_cccd {
                get {
                    try {
                        return ((string)(this[this.tableGET_THONGTINCANBO.ttcb_cmnd_or_cccdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ttcb_cmnd_or_cccd\' in table \'GET_THONGTINCANBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGET_THONGTINCANBO.ttcb_cmnd_or_cccdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ttcb_dantoc {
                get {
                    try {
                        return ((string)(this[this.tableGET_THONGTINCANBO.ttcb_dantocColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ttcb_dantoc\' in table \'GET_THONGTINCANBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGET_THONGTINCANBO.ttcb_dantocColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ttcb_sodienthoai {
                get {
                    try {
                        return ((string)(this[this.tableGET_THONGTINCANBO.ttcb_sodienthoaiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ttcb_sodienthoai\' in table \'GET_THONGTINCANBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGET_THONGTINCANBO.ttcb_sodienthoaiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ttcb_hokhauthuongtru {
                get {
                    try {
                        return ((string)(this[this.tableGET_THONGTINCANBO.ttcb_hokhauthuongtruColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ttcb_hokhauthuongtru\' in table \'GET_THONGTINCANBO\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableGET_THONGTINCANBO.ttcb_hokhauthuongtruColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ttcb_choohiennay {
                get {
                    try {
                        return ((string)(this[this.tableGET_THONGTINCANBO.ttcb_choohiennayColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ttcb_choohiennay\' in table \'GET_THONGTINCANBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGET_THONGTINCANBO.ttcb_choohiennayColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ttcb_hinhanh {
                get {
                    try {
                        return ((string)(this[this.tableGET_THONGTINCANBO.ttcb_hinhanhColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ttcb_hinhanh\' in table \'GET_THONGTINCANBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGET_THONGTINCANBO.ttcb_hinhanhColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string dv_ten {
                get {
                    try {
                        return ((string)(this[this.tableGET_THONGTINCANBO.dv_tenColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'dv_ten\' in table \'GET_THONGTINCANBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGET_THONGTINCANBO.dv_tenColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int kl_loaisuckhoe {
                get {
                    return ((int)(this[this.tableGET_THONGTINCANBO.kl_loaisuckhoeColumn]));
                }
                set {
                    this[this.tableGET_THONGTINCANBO.kl_loaisuckhoeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string kl_ketluantong {
                get {
                    try {
                        return ((string)(this[this.tableGET_THONGTINCANBO.kl_ketluantongColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'kl_ketluantong\' in table \'GET_THONGTINCANBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGET_THONGTINCANBO.kl_ketluantongColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string dksk_ngaykham {
                get {
                    try {
                        return ((string)(this[this.tableGET_THONGTINCANBO.dksk_ngaykhamColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'dksk_ngaykham\' in table \'GET_THONGTINCANBO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGET_THONGTINCANBO.dksk_ngaykhamColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string lslv_ngaybatdaulamviec {
                get {
                    try {
                        return ((string)(this[this.tableGET_THONGTINCANBO.lslv_ngaybatdaulamviecColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'lslv_ngaybatdaulamviec\' in table \'GET_THONGTINCANBO\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableGET_THONGTINCANBO.lslv_ngaybatdaulamviecColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isttcb_hotenNull() {
                return this.IsNull(this.tableGET_THONGTINCANBO.ttcb_hotenColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setttcb_hotenNull() {
                this[this.tableGET_THONGTINCANBO.ttcb_hotenColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isttcb_ngaysinhNull() {
                return this.IsNull(this.tableGET_THONGTINCANBO.ttcb_ngaysinhColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setttcb_ngaysinhNull() {
                this[this.tableGET_THONGTINCANBO.ttcb_ngaysinhColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isttcb_gioitinhNull() {
                return this.IsNull(this.tableGET_THONGTINCANBO.ttcb_gioitinhColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setttcb_gioitinhNull() {
                this[this.tableGET_THONGTINCANBO.ttcb_gioitinhColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isttcb_cmnd_or_cccdNull() {
                return this.IsNull(this.tableGET_THONGTINCANBO.ttcb_cmnd_or_cccdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setttcb_cmnd_or_cccdNull() {
                this[this.tableGET_THONGTINCANBO.ttcb_cmnd_or_cccdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isttcb_dantocNull() {
                return this.IsNull(this.tableGET_THONGTINCANBO.ttcb_dantocColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setttcb_dantocNull() {
                this[this.tableGET_THONGTINCANBO.ttcb_dantocColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isttcb_sodienthoaiNull() {
                return this.IsNull(this.tableGET_THONGTINCANBO.ttcb_sodienthoaiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setttcb_sodienthoaiNull() {
                this[this.tableGET_THONGTINCANBO.ttcb_sodienthoaiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isttcb_hokhauthuongtruNull() {
                return this.IsNull(this.tableGET_THONGTINCANBO.ttcb_hokhauthuongtruColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setttcb_hokhauthuongtruNull() {
                this[this.tableGET_THONGTINCANBO.ttcb_hokhauthuongtruColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isttcb_choohiennayNull() {
                return this.IsNull(this.tableGET_THONGTINCANBO.ttcb_choohiennayColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setttcb_choohiennayNull() {
                this[this.tableGET_THONGTINCANBO.ttcb_choohiennayColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isttcb_hinhanhNull() {
                return this.IsNull(this.tableGET_THONGTINCANBO.ttcb_hinhanhColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setttcb_hinhanhNull() {
                this[this.tableGET_THONGTINCANBO.ttcb_hinhanhColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isdv_tenNull() {
                return this.IsNull(this.tableGET_THONGTINCANBO.dv_tenColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setdv_tenNull() {
                this[this.tableGET_THONGTINCANBO.dv_tenColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Iskl_ketluantongNull() {
                return this.IsNull(this.tableGET_THONGTINCANBO.kl_ketluantongColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setkl_ketluantongNull() {
                this[this.tableGET_THONGTINCANBO.kl_ketluantongColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isdksk_ngaykhamNull() {
                return this.IsNull(this.tableGET_THONGTINCANBO.dksk_ngaykhamColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setdksk_ngaykhamNull() {
                this[this.tableGET_THONGTINCANBO.dksk_ngaykhamColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Islslv_ngaybatdaulamviecNull() {
                return this.IsNull(this.tableGET_THONGTINCANBO.lslv_ngaybatdaulamviecColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setlslv_ngaybatdaulamviecNull() {
                this[this.tableGET_THONGTINCANBO.lslv_ngaybatdaulamviecColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class GET_THONGTINCANBORowChangeEvent : global::System.EventArgs {
            
            private GET_THONGTINCANBORow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GET_THONGTINCANBORowChangeEvent(GET_THONGTINCANBORow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GET_THONGTINCANBORow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591